apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: <POSTGRES_USER>
        - name: SONARQUBE_JDBC_PASSWORD
          value: <POSTGRES_PASSWORD>
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://<DB_HOST>:<DB_PORT>/<DB_NAME>