apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secret
type: Opaque
data:
  username: <DB_USERNAME>
  password: <DB_PASSWORD>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db
  labels:
    app: sonarqube-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-db
  template:
    metadata:
      labels:
        app: sonarqube-db
    spec:
      containers:
      - name: sonarqube-db
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sonarqube-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-db-secret
              key: password
        - name: POSTGRES_DB
          value: <DB_NAME>