apiVersion: v1
kind: Service
metadata:
  name: sonarqube-webhook
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube-webhook
spec:
  rules:
    - host: sonarqube.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarqube-webhook
                port:
                  number: 8080
